service: poppler-service

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'prod'}

layers:
  poppler-layer:
    path: build
    name: poppler-aws-lambda-layer
    description: Poppler v21.06.1
    licenseInfo: GPL-2.0-or-later
    retain: true
    package:
      artifact: build/artifacts.zip
