service: poppler

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'prod'}

layers:
  poppler-layer:
    path: build
    name: poppler-aws-lambda-layer
    description: Poppler v20.10.0
    package:
      artifact: build/artifacts.zip
